run: "test_new_co2_constraint"

logging:
  level: INFO
  format: '%(levelname)s:%(name)s:%(message)s'

scenario:
  lv: [1.0]
  clusters: [37]
  sector_opts: [Co2L-3h-learnH2xElectrolysisp0-learnH2xFuelxCellp0-learnDACp0-learnsolarp0-learnonwindp0-co2seq1, Co2L-3h-learnH2xElectrolysisp0-learnH2xFuelxCellp0-learnDACp0-learnsolarp0-learnonwindp0-co2seq1-local, Co2L-3h-learnH2xElectrolysisp0-learnH2xFuelxCellp0-learnDACp0-learnsolarp0-learnonwindp0-co2seq1-seqcost, Co2L-3h-learnH2xElectrolysisp0-learnH2xFuelxCellp0-learnDACp0-learnsolarp0-learnonwindp0-co2seq1-local-seqcost]
  investment_periods: [2020, 2030, 2040, 2050]

countries: ['AL', 'AT', 'BA', 'BE', 'BG', 'CH', 'CZ', 'DE', 'DK', 'EE', 'ES', 'FI', 'FR', 'GB', 'GR', 'HR', 'HU', 'IE', 'IT', 'LT', 'LU', 'LV', 'ME', 'MK', 'NL', 'NO', 'PL', 'PT', 'RO', 'RS', 'SE', 'SI', 'SK']
# sets technical potential at each bus for renewables
tech_limit: True
# cluster all nodes to one representative
one_node: True
# only select certain countries
select_cts: [] # ["DE", "FR", "GB", "ES"] # ["DE", "FR", "GB", "ES", "DK", "IT", "NO", "CH"]
# upper limit for new capacities of learning technologies
limit_growth: False
# lower limit for new capacities of learning technologies
limit_growth_lb: False
# only used for option seqcost=True, seqcost_update if the capital costs of learning
# technologies before the first initial run should be upated according to DEA
# data set depending on their build year
seqcost_update: True
# option to retrofit existing methane boilers to H2 boilers
h2boiler_retrofit: False

learning_technologies:
  Generator: []  # solar, onwind, offwind-ac, offwind-dc
  StorageUnit: [] # battery, H2
  Store: []
  Link: []  # electrolyzer, DAC?, biomass CCS?

learning_rates:
  solar: 0.24   # DEA p.262 24%,
  solar rooftop: 0.24   # DEA p.262 24%,
  onwind: 0.10  # IRENA 2017 20%, DEA for elec and heat p. 220 assume 10%
  offshore-ac: 0.16  # Bloomberg New Energy Finance 2018, p.242 DEA
  offshore-dc: 0.16
  H2 electrolysis: 0.16  # IRENA between 16-21% https://irena.org/-/media/Files/IRENA/Agency/Publication/2020/Dec/IRENA_Green_hydrogen_cost_2020.pdf
  H2 Electrolysis: 0.16  # IRENA between 16-21% https://irena.org/-/media/Files/IRENA/Agency/Publication/2020/Dec/IRENA_Green_hydrogen_cost_2020.pdf
  H2 fuel cell: 0.16
  H2 Fuel Cell: 0.16
  battery: 0.18  # DEA technology data for energy storage, p.178
  DAC: 0.10  # https://www.sciencedirect.com/science/article/pii/S0959652619307772
  battery charger: 0.19 # battery inverter JRC "Li-ion batteries for mobility and stationary storage applications" p.69

temporal_aggregation:
  n_periods: 4
  hours: 24
  clusterMethod: 'hierarchical' # ['averaging', 'k_means', 'hierarchical', 'k_medoids']
  extremePeriodMethod: 'replace-cluster-center'  # {'None','append','new_cluster_center', 'replace_cluster_center'}
  kind: "storage-constraints"

co2_budget:
  2020: 0.7011648746
  2025: 0.5241935484
  2030: 0.2970430108
  2035: 0.1500896057
  2040: 0.0712365591
  2045: 0.0322580645
  2050: 0
  1p5 : 25 # Budget in Gt CO2 for 1.5 for Europe, global 420 Gt, assuming per capita share
  1p6 : 35  # Budget in Gt CO2 for 1.6 for Europe, global 580 Gt
  1p7 : 48  # Budget in Gt CO2 for 1.7 for Europe, global 800 Gt
  2p0 : 70 # Budget in Gt CO2 for 2 for Europe, global 1170 Gt

sector:
  # TRANSPORT ------------------------------------------------------------
  'bev_dsm' : True #turns on EV battery
  'bev_availability' : 0.5  #How many cars do smart charging
  'v2g' : True #allows feed-in to grid from EV battery
  #what is not EV or FCEV is oil-fuelled ICE
  'land_transport_fuel_cell_share': # 1 means all FCEVs
    2020: 0
    2030: 0.05
    2040: 0.1
    2050: 0.15
  'land_transport_electric_share': # 1 means all EVs
    2020: 0
    2030: 0.25
    2040: 0.6
    2050: 0.85
  'transport_fuel_cell_efficiency': 0.5
  'transport_internal_combustion_efficiency': 0.3
  shipping_average_efficiency: 0.4 #For conversion of fuel oil to propulsion in 2011
  shipping_hydrogen_share: # 1 means all hydrogen FC
    2020: 0
    2025: 0
    2030: 0.05
    2035: 0.15
    2040: 0.3
    2045: 0.6
    2050: 1
    # HEAT --------------------------------------------------------------------
  reduce_space_heat_exogenously: true  # reduces space heat demand by a given factor (applied before losses in DH)
  # this can represent e.g. building renovation, building demolition, or if
  # the factor is negative: increasing floor area, increased thermal comfort, population growth
  reduce_space_heat_exogenously_factor: # per unit reduction in space heat demand
  # the default factors are determined by the LTS scenario from http://tool.european-calculator.eu/app/buildings/building-types-area/?levers=1ddd4444421213bdbbbddd44444ffffff11f411111221111211l212221
    2020: 0.10  # this results in a space heat demand reduction of 10%
    2025: 0.09  # first heat demand increases compared to 2020 because of larger floor area per capita
    2030: 0.09
    2035: 0.11
    2040: 0.16
    2045: 0.21
    2050: 0.29

costs:
  update_costs: False
  year: 2020
  lifetime: 25
  discountrate: 0.07 # From a Lion Hirth paper, also reflects average of Noothout et al 2016
  social_discountrate: 0.00 #0.02
  USD2013_to_EUR2013: 0.7532 # [EUR/USD] ECB: https://www.ecb.europa.eu/stats/exchange/eurofxref/html/eurofxref-graph-usd.en.html
  marginal_cost:
    solar: 0.01
    onwind: 0.015
    offwind: 0.015
    hydro: 0.
    H2: 0.
    battery: 0.
  emission_prices: # in currency per tonne emission, only used with the option Ep
    co2: 0.
  lines:
    length_factor: 1.25 #to estimate offwind connection costs

solving:
  # mem: 30000 #memory in MB; 20 GB enough for 50+B+I+H2; 100 GB for 181+B+I+H2
  options:
    formulation: kirchhoff
    load_shedding: true
    noisy_costs: true
    min_iterations: 4
    max_iterations: 6
    clip_p_max_pu: 0.01
    skip_iterations: false
    track_iterations: false
    #nhours: 10
  solver:
    name: gurobi
    threads: 16
    method: 2 # barrier
    crossover: 0
    BarConvTol: 1.e-5
    FeasibilityTol: 1.e-5
    AggFill: 0
    PreDual: 0
    NodeMethod: 2 # algorithm used for MIP node relaxation, 2=barrier
    MIPGap: 0.05    # 5% gap between (ObjBound-ObjVal)/ObjVal
    MIPFocus: 3
    Cuts: 2
    #ScaleFlag: 0
    Heuristics: 0
    VarBranch: 3   # Mattson p.36 strong branching improved performance
    GURO_PAR_BARDENSETHRESH: 200

plotting:
  map:
    figsize: [7, 7]
    boundaries: [-10.2, 29, 35,  72]
    p_nom:
      bus_size_factor: 5.e+4
      linewidth_factor: 3.e+3

  costs_max: 800
  costs_threshold: 1

  energy_max: 15000.
  energy_min: -10000.
  energy_threshold: 50.

  vre_techs: ["onwind", "offwind-ac", "offwind-dc", "solar", "ror"]
  conv_techs: ["OCGT", "CCGT", "Nuclear", "Coal"]
  storage_techs: ["hydro+PHS", "battery", "H2"]
  load_carriers: ["AC load"]
  AC_carriers: ["AC line", "AC transformer"]
  link_carriers: ["DC line", "Converter AC-DC"]
  tech_colors:
    "onwind" : "#235ebc"
    "onshore wind" : "#235ebc"
    'offwind' : "#6895dd"
    'offwind-ac' : "#6895dd"
    'offshore wind' : "#6895dd"
    'offshore wind ac' : "#6895dd"
    'offshore wind (AC)': "#6895dd"
    'offwind-dc' : "#74c6f2"
    'offshore wind dc' : "#74c6f2"
    'offshore wind (DC)' : "#74c6f2"
    "hydro" : "#08ad97"
    "hydro+PHS" : "#08ad97"
    "PHS" : "#08ad97"
    "hydro reservoir" : "#08ad97"
    'hydroelectricity' : '#08ad97'
    "ror" : "#4adbc8"
    "run of river" : "#4adbc8"
    'solar' : "#f9d002"
    'solar PV' : "#f9d002"
    'solar rooftop' : "#fbe780"
    'solar thermal' : '#eee172'
    'biomass' : '#0c6013'
    'solid biomass' : '#06540d'
    'biogas' : '#23932d'
    'waste' : '#68896b'
    'geothermal' : '#ba91b1'
    "OCGT" : "#e0b487"
    "gas" : "#d9480f"
    "natural gas" : "#d35050"
    "CCGT" : "#b20101"
    "nuclear" : "#ff9000"
    "uranium" : "#f783ac"
    "coal" : "#707070"
    "lignite" : "#9e5a01"
    "oil" : "#262626"
    "H2" : "#ea048a"
    "H2 Store" : "#ea048a"
    "H2 boiler" : "#fd7bc7"
    "H2 electrolysis" : "indigo"
    "H2 Electrolysis" : "indigo"
    "H2 fuel cell" : "thistle"
    "H2 Fuel Cell" : "thistle"
    "load" : "teal"
    "hydrogen storage" : "#ea048a"
    "battery" : "#b8ea04"
    "Li ion" : "#EA04B8"
    "BEV charger" : "#b8ea04"
    "BEV discharger" : "#b8ea04"
    "V2G" : "b"
    "Electric load" : "#f9d002"
    "electricity" : "#f9d002"
    "lines" : "#70af1d"
    "transmission lines" : "#70af1d"
    "AC-AC" : "#70af1d"
    "AC line" : "#70af1d"
    "AC": "silver"
    "H2 pipeline": "silver"
    "links" : "#8a1caf"
    "HVDC links" : "#8a1caf"
    "DC-DC" : "#8a1caf"
    "DC" : "#8a1caf"
    "DC link" : "#8a1caf"
    "CC" : "k"
    "gas boiler" : "#FF922B"
    "SMR" : "#387181"
    "SMR CC" : "#97c5d2"
    "CHP" : "r"
    "DAC": "#d8e9fa"
    "Fischer-Tropsch" : "#44DD33"
    "battery storage" : "#b8ea04"
    "battery charger" : "#e2f69a"
    "air heat pump" : "#b1ff65"
    "ground heat pump" : "#40AA00"
    "resistive heater" : "pink"
    "hot water storage" : "#BBBBBB"
    "Sabatier" : "#FF1493"
    "methanation" : "#620035"
    "helmeth" : "#7D0552"
    "oil boiler" : "#B5A677"
    "process emissions" : "#ced4da"
    "process emissions CC" : "#bbc4b1"
    "solid biomass for industry" : "#62baa0"
    "solid biomass for industry CC" : "#98d2c1"
    "gas for industry" : "#ef5d5d"
    "gas for industry CC" : "#8e0e0e"
    "electricity distribution grid" : "#C8C8A9"
    "co2 vent": "b"
    "co2": "b"
    "co2 stored": "b"
    'CO2 sequestration': "b"
    "biogas to gas" : "#800000"
    "low voltage": "#c6c6c6"
    "heat": "#ff8585"

  nice_names:
    OCGT: "Open-Cycle Gas"
    CCGT: "Combined-Cycle Gas"
    offwind-ac: "Offshore Wind (AC)"
    offwind-dc: "Offshore Wind (DC)"
    onwind: "Onshore Wind"
    solar: "Solar"
    PHS: "Pumped Hydro Storage"
    hydro: "Reservoir & Dam"
    battery: "Battery Storage"
    H2: "Hydrogen Storage"
    lines: "Transmission Lines"
    ror: "Run of River"
