name: learning_curve
channels:
  - gurobi
  - anaconda
  - http://conda.anaconda.org/gurobi
  - conda-forge
  - https://conda.anaconda.org/gurobi
  - defaults
dependencies:
  - _libgcc_mutex
  - _openmp_mutex
  - ampl-mp
  - appdirs
  - backcall
  - ca-certificates
  - certifi
  - cycler
  - dbus
  - decorator
  - expat
  - fontconfig
  - freetype
  - gettext
  - glib
  - glib-tools
  - gst-plugins-base
  - gstreamer
  - gurobi
  - icu
  - ipopt
  - ipykernel
  - ipython
  - ipython_genutils
  - jedi
  - jpeg
  - jupyter_client
  - jupyter_core
  - kiwisolver
  - krb5
  - lcms2
  - ld_impl_linux-64
  - libblas
  - libcblas
  - libclang
  - libedit
  - libevent
  - libffi
  - libgcc-ng
  - libgfortran-ng
  - libgfortran4
  - libgfortran5
  - libglib
  - libgomp
  - libiconv
  - liblapack
  - libllvm11
  - libopenblas
  - libpng
  - libpq
  - libsodium
  - libstdcxx-ng
  - libtiff
  - libuuid
  - libwebp-base
  - libxcb
  - libxkbcommon
  - libxml2
  - lz4-c
  - matplotlib
  - matplotlib-base
  - metis
  - mumps-include
  - mumps-seq
  - mysql-common
  - mysql-libs
  - ncurses
  - nose
  - nspr
  - nss
  - numpy
  - olefile
  - openssl
  - pandas
  - parso
  - pcre
  - pexpect
  - pickleshare
  - pillow
  - pip
  - ply
  - prompt-toolkit
  - ptyprocess
  - pygments
  - pyomo
  - pyparsing
  - pyqt
  - pyqt-impl
  - pyqt5-sip
  - pyqtchart
  - pyqtwebengine
  - python
  - python-dateutil
  - python_abi
  - pytz
  - pyutilib
  - pyzmq
  - qt
  - readline
  - scotch
  - setuptools
  - six
  - sqlite
  - tk
  - tornado
  - traitlets
  - tzdata
  - wcwidth
  - wheel
  - xz
  - zeromq
  - zlib
  - zstd
